export const newsItems = {"articles":
[
  {"title":"WHO: En ”perfekt storm” – kan hända var som helst",
  "text":"WHO gick under torsdagen ut med en varning riktad till europeiska länder om att lättade coronarestriktioner kan skapa en ”perfekt storm” och leda till skenande smittspridning – som i Indien. Det skriver AFP. – Det är väldigt viktigt att inse att situationen i Indien kan uppkomma varsomhelst, säger organisationens Europachef Hans Kluge. ",
  "href":"https://omni.se/who-en-perfekt-storm-kan-handa-var-som-helst/a/bnPA9l",
  "imgSrc":"https://gfx.omni.se/images/f27f8fdb-99db-4ef9-b85d-b337327288e0?h=180&tight=true&w=180",
  "imgTitle":"Massbegravningar i New Delhi. Altaf Qadri / TT NYHETSBYRÅN"},
  {"title":"Trumps försvar efter razzia: ’New Yorks bästa borgmästare’",
    "text":"Federala utredare genomförde en husrannsakan mot Rudy Giulianis lägenhet i New York under onsdagen, som en del av en brottsutredning om Giulianis affärer i Ukraina.Donald Trump försvarade sin tidigare advokat under torsdagen och sa bland annat att han är ”den bästa borgmästaren i New Yorks historia” och ”en sann patriot”, skriver The Guardian. ",
    "href":"https://omni.se/trumps-forsvar-efter-razzia-new-yorks-basta-borgmastare/a/0K85jA",
    "imgSrc":"https://gfx.omni.se/images/83e4c6d2-b294-45b6-9781-34833473502e?h=180&tight=true&w=180",
    "imgTitle":"Giuliani. Mike Mulholland / TT NYHETSBYRÅN"},
  {"title":"MP: Hemarbete är bra, men öppna när vaccinmålet nås",
    "text":"Karensdagen bör inte återinföras och mer hemarbete bör välkomnas även i framtiden, men i övrigt så bör dagens restriktioner avskaffas när Sverige nått vaccinationsmålet. Det skriver Miljöpartiets Rasmus Ling på Facebook efter att regeringspartnern och socialministern Lena Hallengren (S) tidigare under onsdagen låtit meddela att Folkhälsomyndigheten ska analysera vilka restriktioner och åtgärder som kan finnas kvar vid ett eventuellt ”nytt normalläge” i framtiden. ”Det är helt orimligt att tänka sig ett samhälle där vi inte får umgås, gå på arrangemang, äta och dricka tillsammans, demonstrera, resa”, skriver Ling. Flera politiker har yttrat kritik efter att Hallengren sagt hon tror att många förstår att samhället inte kommer vara som innan pandemin i full utsträckning, och krävt att ministern förtydligar. ",
    "href":"https://omni.se/mp-hemarbete-ar-bra%2C-men-oppna-nar-vaccinmalet-nas/a/Alnedr",
    "imgSrc":"https://gfx.omni.se/images/e422db9a-6db8-472a-bc54-7d5ef6a8af3e?h=180&tight=true&w=180",
    "imgTitle":"MP:s Rasmus Ling.  Claudio Bresciani/TT / TT NYHETSBYRÅN"},
  {"title":"MP: Hemarbete är bra, men öppna när vaccinmålet nås",
    "text":"Karensdagen bör inte återinföras och mer hemarbete bör välkomnas även i framtiden, men i övrigt så bör dagens restriktioner avskaffas när Sverige nått vaccinationsmålet. Det skriver Miljöpartiets Rasmus Ling på Facebook efter att regeringspartnern och socialministern Lena Hallengren (S) tidigare under onsdagen låtit meddela att Folkhälsomyndigheten ska analysera vilka restriktioner och åtgärder som kan finnas kvar vid ett eventuellt ”nytt normalläge” i framtiden. ”Det är helt orimligt att tänka sig ett samhälle där vi inte får umgås, gå på arrangemang, äta och dricka tillsammans, demonstrera, resa”, skriver Ling. Flera politiker har yttrat kritik efter att Hallengren sagt hon tror att många förstår att samhället inte kommer vara som innan pandemin i full utsträckning, och krävt att ministern förtydligar. ",
    "href":"https://omni.se/mp-hemarbete-ar-bra%2C-men-oppna-nar-vaccinmalet-nas/a/Alnedr",
    "imgSrc":"https://gfx.omni.se/images/e422db9a-6db8-472a-bc54-7d5ef6a8af3e?h=180&tight=true&w=180",
    "imgTitle":"MP:s Rasmus Ling.  Claudio Bresciani/TT / TT NYHETSBYRÅN"},
  {"title":"MP: Hemarbete är bra, men öppna när vaccinmålet nås",
    "text":"Karensdagen bör inte återinföras och mer hemarbete bör välkomnas även i framtiden, men i övrigt så bör dagens restriktioner avskaffas när Sverige nått vaccinationsmålet. Det skriver Miljöpartiets Rasmus Ling på Facebook efter att regeringspartnern och socialministern Lena Hallengren (S) tidigare under onsdagen låtit meddela att Folkhälsomyndigheten ska analysera vilka restriktioner och åtgärder som kan finnas kvar vid ett eventuellt ”nytt normalläge” i framtiden. ”Det är helt orimligt att tänka sig ett samhälle där vi inte får umgås, gå på arrangemang, äta och dricka tillsammans, demonstrera, resa”, skriver Ling. Flera politiker har yttrat kritik efter att Hallengren sagt hon tror att många förstår att samhället inte kommer vara som innan pandemin i full utsträckning, och krävt att ministern förtydligar. ",
    "href":"https://omni.se/mp-hemarbete-ar-bra%2C-men-oppna-nar-vaccinmalet-nas/a/Alnedr",
    "imgSrc":"https://gfx.omni.se/images/e422db9a-6db8-472a-bc54-7d5ef6a8af3e?h=180&tight=true&w=180",
    "imgTitle":"MP:s Rasmus Ling.  Claudio Bresciani/TT / TT NYHETSBYRÅN"},
  {"title":"MP: Hemarbete är bra, men öppna när vaccinmålet nås",
    "text":"Karensdagen bör inte återinföras och mer hemarbete bör välkomnas även i framtiden, men i övrigt så bör dagens restriktioner avskaffas när Sverige nått vaccinationsmålet. Det skriver Miljöpartiets Rasmus Ling på Facebook efter att regeringspartnern och socialministern Lena Hallengren (S) tidigare under onsdagen låtit meddela att Folkhälsomyndigheten ska analysera vilka restriktioner och åtgärder som kan finnas kvar vid ett eventuellt ”nytt normalläge” i framtiden. ”Det är helt orimligt att tänka sig ett samhälle där vi inte får umgås, gå på arrangemang, äta och dricka tillsammans, demonstrera, resa”, skriver Ling. Flera politiker har yttrat kritik efter att Hallengren sagt hon tror att många förstår att samhället inte kommer vara som innan pandemin i full utsträckning, och krävt att ministern förtydligar. ",
    "href":"https://omni.se/mp-hemarbete-ar-bra%2C-men-oppna-nar-vaccinmalet-nas/a/Alnedr",
    "imgSrc":"https://gfx.omni.se/images/e422db9a-6db8-472a-bc54-7d5ef6a8af3e?h=180&tight=true&w=180",
    "imgTitle":"MP:s Rasmus Ling.  Claudio Bresciani/TT / TT NYHETSBYRÅN"},
  {"title":"MP: Hemarbete är bra, men öppna när vaccinmålet nås",
    "text":"Karensdagen bör inte återinföras och mer hemarbete bör välkomnas även i framtiden, men i övrigt så bör dagens restriktioner avskaffas när Sverige nått vaccinationsmålet. Det skriver Miljöpartiets Rasmus Ling på Facebook efter att regeringspartnern och socialministern Lena Hallengren (S) tidigare under onsdagen låtit meddela att Folkhälsomyndigheten ska analysera vilka restriktioner och åtgärder som kan finnas kvar vid ett eventuellt ”nytt normalläge” i framtiden. ”Det är helt orimligt att tänka sig ett samhälle där vi inte får umgås, gå på arrangemang, äta och dricka tillsammans, demonstrera, resa”, skriver Ling. Flera politiker har yttrat kritik efter att Hallengren sagt hon tror att många förstår att samhället inte kommer vara som innan pandemin i full utsträckning, och krävt att ministern förtydligar. ",
    "href":"https://omni.se/mp-hemarbete-ar-bra%2C-men-oppna-nar-vaccinmalet-nas/a/Alnedr",
    "imgSrc":"https://gfx.omni.se/images/e422db9a-6db8-472a-bc54-7d5ef6a8af3e?h=180&tight=true&w=180",
    "imgTitle":"MP:s Rasmus Ling.  Claudio Bresciani/TT / TT NYHETSBYRÅN"},
]}

//TODO REMOVE THIS

export default newsItems;
